# DATA ACQUISITION & FILTERING

In [1]:
# STAGE 2: DATA ACQUISITION & FILTERING
# Acquire the required data from the dataset

import pandas as pd

file_path = "/content/india_road_accidents.csv"
df = pd.read_csv(file_path)

print("Dataset acquired successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nAvailable Columns:")
print(df.columns.tolist())

Dataset acquired successfully!
Rows: 240
Columns: 25

Available Columns:
['accident_id', 'date_time', 'year', 'month', 'state_ut', 'district', 'road_type', 'weather', 'road_surface', 'lighting', 'vehicle_type', 'driver_age_group', 'driver_gender', 'speed_limit_kmph', 'estimated_speed_kmph', 'alcohol_involved', 'helmet_seatbelt_used', 'severity', 'fatalities', 'severe_injuries', 'minor_injuries', 'primary_cause', 'pedestrians_involved', 'latitude', 'longitude']

In [2]:

# Select the important columns needed for analysis

required_columns = [
    "state_ut",
    "district",
    "road_type",
    "weather",
    "severity",
    "primary_cause",
    "fatalities",
    "severe_injuries",
    "minor_injuries"
]

acquired_data = df[required_columns]

print("Required data acquired successfully!")
print("Rows:", acquired_data.shape[0])
print("Columns:", acquired_data.shape[1])

acquired_data.head()

Required data acquired successfully!
Rows: 240
Columns: 9

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
2,Punjab,Patiala,National Highway,Clear,Minor Injury,Fatigue / Sleep,0,0,1
3,Odisha,Sambalpur,City Road,Extreme Heat,Minor Injury,Mobile Phone Use,0,0,2
4,Rajasthan,Ajmer,State Highway,DENSE FOG,Minor Injury,Red Light / Signal Jump,0,0,1

In [ ]:
# Create a dataset containing only accident records needed for further analysis

analysis_data = acquired_data[
    [
        "state_ut",
        "district",
        "road_type",
        "weather",
        "severity",
        "primary_cause",
        "fatalities",
        "severe_injuries",
        "minor_injuries"
    ]
].copy()

print("Analysis data acquired successfully!")
print("Rows:", len(analysis_data))
print("Columns:", len(analysis_data.columns))

analysis_data.head()

In [ ]:
# Create a smaller dataset for accident outcome analysis

outcome_data = analysis_data[
    [
        "severity",
        "fatalities",
        "severe_injuries",
        "minor_injuries"
    ]
].copy()

print("Outcome data extracted successfully!")
print("Rows:", len(outcome_data))
print("Columns:", len(outcome_data.columns))

outcome_data.head()

In [3]:

# Filter the data for fatal accidents

fatal_accidents = acquired_data[acquired_data["severity"] == "Fatal"]

print("Fatal accidents:", len(fatal_accidents))
fatal_accidents.head()

Fatal accidents: 103

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0

In [4]:
# Filter by road type

national_highway = acquired_data[
    acquired_data["road_type"] == "National Highway"
]

print("National Highway accidents:", len(national_highway))
national_highway.head()

National Highway accidents: 66

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
2,Punjab,Patiala,National Highway,Clear,Minor Injury,Fatigue / Sleep,0,0,1
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
9,Maharashtra,Thane,National Highway,Dense Fog,Fatal,Overspeeding,1,0,1
11,West Bengal,Siliguri,National Highway,Clear,Fatal,Mobile Phone Use,2,1,1

In [5]:
# Filter by weather condition

heavy_rain = acquired_data[
    acquired_data["weather"] == "Heavy Rain"
]

print("Heavy Rain accidents:", len(heavy_rain))
heavy_rain.head()

Heavy Rain accidents: 39

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
10,Bihar,Gaya,Expressway,Heavy Rain,Fatal,Fatigue / Sleep,2,2,1
12,Odisha,Cuttack,City Road,Heavy Rain,Minor Injury,Red Light / Signal Jump,0,0,2
13,Maharashtra,Thane,NATIONAL HIGHWAY,Heavy Rain,Fatal,Drunk Driving,2,1,1
14,Andhra Pradesh,Guntur,National Highway,Heavy Rain,Grievous Injury,Overspeeding,0,2,0

In [6]:
# Filter by a specific state

telangana_accidents = acquired_data[
    acquired_data["state_ut"] == "Telangana"
]

print("Telangana accidents:", len(telangana_accidents))
telangana_accidents.head()

Telangana accidents: 15

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
35,Telangana,Warangal,National Highway,Heavy Rain,Grievous Injury,Overspeeding,0,2,1
69,Telangana,Warangal,State Highway,Clear,Fatal,Drunk Driving,1,2,0
76,Telangana,Hyderabad,City Road,Clear,Fatal,Drunk Driving,2,0,0
99,Telangana,nizamabad,Rural Road,CLEAR,Minor Injury,fatigue / sleep,0,0,1

In [7]:
# Filter accidents by both state and severity

telangana_fatal = acquired_data[
    (acquired_data["state_ut"] == "Telangana") &
    (acquired_data["severity"] == "Fatal")
]

print("Fatal accidents in Telangana:", len(telangana_fatal))
telangana_fatal.head()

Fatal accidents in Telangana: 8

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
69,Telangana,Warangal,State Highway,Clear,Fatal,Drunk Driving,1,2,0
76,Telangana,Hyderabad,City Road,Clear,Fatal,Drunk Driving,2,0,0
144,Telangana,karimnagar,State Highway,Dense Fog,Fatal,Overspeeding,1,1,1
147,Telangana,Warangal,State Highway,Clear,Fatal,DRUNK DRIVING,1,1,1

In [8]:
# Filter accidents with high-severity outcomes

serious_accidents = acquired_data[
    acquired_data["severity"].isin(["Fatal", "Grievous Injury"])
]

print("Serious accidents:", len(serious_accidents))
serious_accidents.head()

Serious accidents: 175

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0

In [9]:
# Filter accidents caused by overspeeding

overspeeding_accidents = acquired_data[
    acquired_data["primary_cause"] == "Overspeeding"
]

print("Overspeeding accidents:", len(overspeeding_accidents))
overspeeding_accidents.head()

Overspeeding accidents: 67

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0
8,Karnataka,Hubballi,State Highway,Dense Fog,Grievous Injury,Overspeeding,0,2,1

In [11]:
# Filter only fatal accidents

fatal_data = acquired_data[
    acquired_data["severity"] == "Fatal"
]

print("Fatal accidents:", len(fatal_data))
fatal_data.head()

Fatal accidents: 103

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0

In [12]:
# Filter accidents with at least one fatality

fatality_records = acquired_data[
    acquired_data["fatalities"] > 0
]

print("Accidents with fatalities:", len(fatality_records))
fatality_records.head()

Accidents with fatalities: 118

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0

In [13]:
# Filter accidents with severe injuries

severe_injury_records = acquired_data[
    acquired_data["severe_injuries"] > 0
]

print("Accidents with severe injuries:", len(severe_injury_records))
severe_injury_records.head()

Accidents with severe injuries: 156

,state_ut,district,road_type,weather,severity,primary_cause,fatalities,severe_injuries,minor_injuries
0,Karnataka,Mangaluru,National Highway,Dense Fog,Fatal,Overspeeding,1,2,0
1,Telangana,Khammam,State Highway,Dense Fog,Fatal,Overspeeding,1,1,0
5,Odisha,Puri,City Road,Heavy Rain,Fatal,Overspeeding,1,2,0
6,Assam,Dibrugarh,National Highway,Extreme Heat,Fatal,Drunk Driving,2,1,0
7,Delhi NCR,Ghaziabad,City Road,Clear,Fatal,Overspeeding,1,1,0