In [ ]:
import pandas as pd

# Load the dataset
file_path = "/content/india_road_accidents.csv"

In [ ]:
df = pd.read_csv(file_path)

In [ ]:
# Display basic dataset information
print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully!
Number of rows: 240
Number of columns: 25

In [ ]:
# Display first 5 records
print("\nFirst 5 records:")
display(df.head())

First 5 records:

,accident_id,date_time,year,month,state_ut,district,road_type,weather,road_surface,lighting,...,alcohol_involved,helmet_seatbelt_used,severity,fatalities,severe_injuries,minor_injuries,primary_cause,pedestrians_involved,latitude,longitude
0,IND-2022-0001,10-01-2022 05:15,2022,Jan,Karnataka,Mangaluru,National Highway,Dense Fog,Dry,Dark / No Lights,...,False,True,Fatal,1,2,0,Overspeeding,False,16.3500,72.4217
1,IND-2022-0002,17/08/2022 04:56,2022,Aug,Telangana,Khammam,State Highway,Dense Fog,Dry,Dark / No Lights,...,False,True,Fatal,1,1,0,Overspeeding,True,26.8094,82.9490
2,IND-2021-0003,17-09-2021 07:04,2021,sep,Punjab,Patiala,National Highway,Clear,DRY,Daylight,...,False,True,Minor Injury,0,0,1,Fatigue / Sleep,False,25.4819,72.1585
3,IND-2022-0004,21/02/2022 20:34,2022,Feb,Odisha,Sambalpur,City Road,Extreme Heat,Dry,Street Lights On,...,False,True,Minor Injury,0,0,2,Mobile Phone Use,False,28.6459,76.4460
4,IND-2021-0005,20-02-2021 05:34,2021,Feb,Rajasthan,Ajmer,State Highway,DENSE FOG,Wet,Dark / No Lights,...,False,False,Minor Injury,0,0,1,Red Light / Signal Jump,False,26.0421,74.4409

In [ ]:
# Display the last 5 records
df.tail()

,accident_id,date_time,year,month,state_ut,district,road_type,weather,road_surface,lighting,...,alcohol_involved,helmet_seatbelt_used,severity,fatalities,severe_injuries,minor_injuries,primary_cause,pedestrians_involved,latitude,longitude
235,IND-2021-0236,23-05-2021 02:02,2021,May,Bihar,Bhagalpur,National Highway,Clear,Dry,Dark / No Lights,...,False,False,Grievous Injury,0,2,0,Weather Visibility,False,20.2144,87.2367
236,IND-2022-0237,13-06-2022 01:25,2022,Jun,Delhi NCR,NOIDA,State Highway,Unknown,Wet,Dark / No Lights,...,False,True,Minor Injury,0,0,3,Red Light / Signal Jump,False,26.3884,79.3428
237,IND-2023-0238,10-09-2023 04:58,2023,Sep,Rajasthan,Jaipur,CITY ROAD,NaN,Wet,Dark / No Lights,...,False,False,Grievous Injury,0,3,1,Wrong-Side Driving,False,25.0747,76.7760
238,IND-2021-0239,20-09-2021 11:19,2021,Sep,Maharashtra,Mumbai,city road,Dust Storm,Loose Gravel,DAYLIGHT,...,True,False,Minor Injury,0,0,1,Drunk Driving,False,16.3213,69.4486
239,IND-2022-0240,2022-01-28 15:50,2022,Jan,telangana,Hyderabad,National Highway,heavy rain,Wet,Daylight,...,False,Y,Fatal,2,1,0,Overspeeding,True,22.4127,85.1695

In [ ]:
# Display all column names
print("Column Names:")
print(df.columns.tolist())

Column Names:
['accident_id', 'date_time', 'year', 'month', 'state_ut', 'district', 'road_type', 'weather', 'road_surface', 'lighting', 'vehicle_type', 'driver_age_group', 'driver_gender', 'speed_limit_kmph', 'estimated_speed_kmph', 'alcohol_involved', 'helmet_seatbelt_used', 'severity', 'fatalities', 'severe_injuries', 'minor_injuries', 'primary_cause', 'pedestrians_involved', 'latitude', 'longitude']

In [ ]:
# Check the data type of each column
print("Data Types of Each Column:")
print(df.dtypes)

Data Types of Each Column:
accident_id              object
date_time                object
year                      int64
month                    object
state_ut                 object
district                 object
road_type                object
weather                  object
road_surface             object
lighting                 object
vehicle_type             object
driver_age_group         object
driver_gender            object
speed_limit_kmph         object
estimated_speed_kmph     object
alcohol_involved         object
helmet_seatbelt_used     object
severity                 object
fatalities                int64
severe_injuries           int64
minor_injuries            int64
primary_cause            object
pedestrians_involved     object
latitude                float64
longitude               float64
dtype: object

In [ ]:
# Display complete dataset information
print("Dataset Information:")
print("--------------------")

df.info()

Dataset Information:
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   accident_id           240 non-null    object
 1   date_time             240 non-null    object
 2   year                  240 non-null    int64
 3   month                 240 non-null    object
 4   state_ut              240 non-null    object
 5   district              240 non-null    object
 6   road_type             240 non-null    object
 7   weather               236 non-null    object
 8   road_surface          237 non-null    object
 9   lighting              237 non-null    object
 10  vehicle_type          240 non-null    object
 11  driver_age_group      240 non-null    object
 12  driver_gender         240 non-null    object
 13  speed_limit_kmph      240 non-null    object
 14  estimated_speed_kmph  237 non-null    object
 15  alcohol_involved      240 non-null    object
 16  helmet_seatbelt_used  240 non-null    object
 17  severity              240 non-null    object
 18  fatalities            240 non-null    int64
 19  severe_injuries       240 non-null    int64
 20  minor_injuries        240 non-null    int64
 21  primary_cause         237 non-null    object
 22  pedestrians_involved  240 non-null    object
 23  latitude              240 non-null    float64
 24  longitude             240 non-null    float64
dtypes: float64(2), int64(4), object(19)
memory usage: 47.0+ KB

In [ ]:
# Generate statistical summary for numerical columns
print("Statistical Summary of Numerical Columns:")
print("-----------------------------------------")

display(df.describe())

Statistical Summary of Numerical Columns:
-----------------------------------------

,year,fatalities,severe_injuries,minor_injuries,latitude,longitude
count,240.000000,240.000000,240.000000,240.000000,240.000000,240.000000
mean,2022.545833,0.712500,1.129167,0.662500,19.319937,79.037508
std,1.170588,0.805739,1.008325,0.742219,6.772018,7.134810
min,2021.000000,0.000000,0.000000,0.000000,8.275700,68.055100
25%,2021.000000,0.000000,0.000000,0.000000,13.755150,72.566950
50%,2023.000000,0.000000,1.000000,1.000000,19.316850,78.211200
75%,2024.000000,1.000000,2.000000,1.000000,25.081850,84.336050
max,2024.000000,2.000000,3.000000,3.000000,31.720800,91.981100

In [ ]:
# Check memory usage of the dataset
print("Memory Usage by Column:")
print("-----------------------")

display(df.memory_usage(deep=True))

print("\nTotal Memory Usage:")
print(df.memory_usage(deep=True).sum(), "bytes")

Memory Usage by Column:
-----------------------

Index                     132
accident_id             14880
date_time               15620
year                     1920
month                   12498
state_ut                13959
district                13516
road_type               14731
weather                 13623
road_surface            13206
lighting                14457
vehicle_type            14833
driver_age_group        13207
driver_gender           12810
speed_limit_kmph        12356
estimated_speed_kmph    12368
alcohol_involved        12843
helmet_seatbelt_used    12795
severity                14095
fatalities               1920
severe_injuries          1920
minor_injuries           1920
primary_cause           15335
pedestrians_involved    12824
latitude                 1920
longitude                1920
dtype: int64

Total Memory Usage:
271608 bytes

In [ ]:
# Identify numerical columns
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

print("Numerical Columns:")
print("------------------")

for i, column in enumerate(numerical_columns, start=1):
    print(i, ".", column)

print("\nTotal Numerical Columns:", len(numerical_columns))

Numerical Columns:
------------------
1 . year
2 . fatalities
3 . severe_injuries
4 . minor_injuries
5 . latitude
6 . longitude

Total Numerical Columns: 6

In [ ]:
# Identify categorical columns
categorical_columns = df.select_dtypes(include=["object"]).columns

print("Categorical Columns:")
print("--------------------")

for i, column in enumerate(categorical_columns, start=1):
    print(i, ".", column)

print("\nTotal Categorical Columns:", len(categorical_columns))

Categorical Columns:
--------------------
1 . accident_id
2 . date_time
3 . month
4 . state_ut
5 . district
6 . road_type
7 . weather
8 . road_surface
9 . lighting
10 . vehicle_type
11 . driver_age_group
12 . driver_gender
13 . speed_limit_kmph
14 . estimated_speed_kmph
15 . alcohol_involved
16 . helmet_seatbelt_used
17 . severity
18 . primary_cause
19 . pedestrians_involved

Total Categorical Columns: 19